project:
  type: website
  render:
    - index.qmd
    - sessions/api.qmd

custom-callout:
  exercise:
    icon-symbol: "📝 "
    color: "pink"

filters:
  - custom-callout
  - "vscode.lua"

lang: fr

website:
  title: "Atelier du `SSPHub`"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "sessions/api.qmd"
        text: API


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-annotations: hover
    code-link: true
