name: Publish slides

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: inseefrlab/onyxia-rstudio:r4.3.3-2025.04.07
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libfontconfig1-dev \
            libharfbuzz-dev libfribidi-dev
          cp pyprojects/api.toml pyproject.toml
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: |
            pip install uv
            uv pip install -r pyproject.toml --system
      - uses: r-lib/actions/setup-r@v2
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.6.42
      - name: Render website
        run: |
          quarto render --to html
          quarto render sessions/api.qmd --to ipynb  --execute
          mkdir -p temp_notebooks
          cp _site/sessions/api.ipynb temp_notebooks/api.ipynb
        env:
            TOKEN_API_INSEE:  ${{ secrets.TOKEN_API_INSEE }}
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: "false"
      - name: Pushes to another repository
        uses: linogaliana/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'temp_notebooks/'
          destination-repository-username: 'linogaliana'
          destination-repository-name: 'https://github.com/linogaliana/ssphub-ateliers-notebooks.git'
          user-email: lino.galiana@insee.fr
          destination-github-username: linogaliana
          #target-branch: test
          create-target-branch-if-needed: true
          reset-repo: true
